# Generated by Django 2.2.14 on 2021-12-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('Name', models.CharField(max_length=500)),
                ('price', models.IntegerField(max_length=30)),
            ],
        ),
    ]
