# Generated by Django 2.2.14 on 2021-12-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211222_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='backimage',
            name='adress',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backimage',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='backimage',
            name='number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
