# Generated by Django 2.2.14 on 2021-12-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211222_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backimage',
            name='adress',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='backimage',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='backimage',
            name='number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
